// Tab 03 — The Boom
// Postwar homeownership by race, FHA lending, Levittown, compounding calculator.

function TabBoom() {
  const timeline = useData('data/homeownership_timeline.json');
  const wealth = useData('data/wealth_gap.json');
  const [calcYear, setCalcYear] = React.useState(1950);
  const [calcPrice, setCalcPrice] = React.useState(10000);

  // Simple appreciation model: 4.5% annual avg for homes
  const currentValue = Math.round(calcPrice * Math.pow(1.045, 2024 - calcYear));
  const gain = currentValue - calcPrice;

  return (
    <div style={{ padding: '32px 48px' }}>
      <SectionHead
        label="03 · The Boom"
        title="The wealth that was withheld."
        subtitle="The US homeownership rate rose from 43.6% to over 60% between 1940 and 1960. The wealth generated by that expansion went almost entirely to white families."
      />

      {/* Homeownership gap chart */}
      {timeline && (
        <div style={{ marginBottom: 40 }}>
          <Tick style={{ color: 'var(--gold)', fontWeight: 700, marginBottom: 12, display: 'block' }}>Homeownership Rate by Race, 1940–2024</Tick>
          <svg viewBox="0 0 900 340" style={{ width: '100%', maxWidth: 900, display: 'block', overflow: 'visible' }}>
            {/* Grid */}
            {[20, 30, 40, 50, 60, 70, 80].map(v => (
              <React.Fragment key={v}>
                <line x1={60} y1={300 - (v - 20) * 4} x2={880} y2={300 - (v - 20) * 4} stroke="var(--line)" strokeWidth="0.5" />
                <text x={55} y={300 - (v - 20) * 4 + 4} textAnchor="end" fill="var(--ink-dimmer)" fontSize="10" fontFamily="Space Mono">{v}%</text>
              </React.Fragment>
            ))}

            {/* Year labels */}
            {timeline.filter((_, i) => i % 2 === 0).map(d => {
              const x = 60 + ((d.year - 1940) / 84) * 820;
              return <text key={d.year} x={x} y={320} textAnchor="middle" fill="var(--ink-dimmer)" fontSize="9" fontFamily="Space Mono">{d.year}</text>;
            })}

            {/* White line */}
            <polyline fill="none" stroke="var(--ink)" strokeWidth="2.5"
              points={timeline.map(d => `${60 + ((d.year - 1940) / 84) * 820},${300 - (d.white - 20) * 4}`).join(' ')} />

            {/* Black line */}
            <polyline fill="none" stroke="var(--grade-d)" strokeWidth="2.5"
              points={timeline.map(d => `${60 + ((d.year - 1940) / 84) * 820},${300 - (d.black - 20) * 4}`).join(' ')} />

            {/* Gap shading */}
            <polygon fill="rgba(192,57,43,0.08)"
              points={[
                ...timeline.map(d => `${60 + ((d.year - 1940) / 84) * 820},${300 - (d.white - 20) * 4}`),
                ...timeline.slice().reverse().map(d => `${60 + ((d.year - 1940) / 84) * 820},${300 - (d.black - 20) * 4}`),
              ].join(' ')} />

            {/* Fair Housing Act marker */}
            <line x1={60 + ((1968 - 1940) / 84) * 820} y1={40} x2={60 + ((1968 - 1940) / 84) * 820} y2={300} stroke="var(--gold)" strokeWidth="1" strokeDasharray="4 3" />
            <text x={60 + ((1968 - 1940) / 84) * 820} y={35} textAnchor="middle" fill="var(--gold)" fontSize="9" fontFamily="Space Mono">Fair Housing Act 1968</text>

            {/* Labels */}
            <text x={870} y={300 - (timeline[timeline.length-1].white - 20) * 4 - 6} fill="var(--ink)" fontSize="11" fontFamily="Space Mono" fontWeight="700">White {timeline[timeline.length-1].white}%</text>
            <text x={870} y={300 - (timeline[timeline.length-1].black - 20) * 4 + 14} fill="var(--grade-d)" fontSize="11" fontFamily="Space Mono" fontWeight="700">Black {timeline[timeline.length-1].black}%</text>

            {/* Gap annotation */}
            {(() => {
              const last = timeline[timeline.length - 1];
              const midY = 300 - ((last.white + last.black) / 2 - 20) * 4;
              return <text x={860} y={midY + 4} textAnchor="end" fill="var(--ink-dim)" fontSize="10" fontFamily="Space Mono">Gap: {last.gap}pp</text>;
            })()}
          </svg>

          <div className="serif" style={{ fontSize: 14, fontStyle: 'italic', color: 'var(--ink-dim)', marginTop: 12, maxWidth: 640 }}>
            The gap is wider today than it was in 1960, when housing discrimination was still legal.
          </div>
        </div>
      )}

      {/* Levittown + FHA */}
      {wealth && (
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 24, marginBottom: 40 }}>
          <div style={{ background: 'var(--bg-2)', border: '1px solid var(--line)', padding: 24, borderRadius: 4 }}>
            <Tick style={{ color: 'var(--gold)', fontWeight: 700 }}>The Levittown Calculation</Tick>
            <div className="garamond" style={{ fontSize: 20, color: 'var(--ink)', marginTop: 8 }}>One house. Three generations.</div>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginTop: 16 }}>
              <StatBlock label="Purchase Price (1947)" value={`$${fmt(wealth.levittown.purchase_price)}`} color="var(--ink)" />
              <StatBlock label="Current Value" value={`$${fmt(wealth.levittown.current_value)}`} color="var(--grade-a)" />
            </div>
            <div className="serif" style={{ fontSize: 13, color: 'var(--ink-dim)', fontStyle: 'italic', marginTop: 16, lineHeight: 1.6 }}>
              Levittown was built with FHA backing and was explicitly whites-only by developer covenant. The family that bought in 1947 generated ~$412,000 in wealth from one transaction that Black families were legally prevented from making.
            </div>
          </div>

          <div style={{ background: 'var(--bg-2)', border: '1px solid var(--line)', padding: 24, borderRadius: 4 }}>
            <Tick style={{ color: 'var(--gold)', fontWeight: 700 }}>FHA Lending</Tick>
            <div className="garamond" style={{ fontSize: 20, color: 'var(--ink)', marginTop: 8 }}>$120 billion in mortgages. 2% went to families of color.</div>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginTop: 16 }}>
              <StatBlock label="GI Bill Mortgages (NY/NJ 1950)" value={fmt(wealth.levittown.gi_bill_mortgages_ny_nj_1950)} color="var(--ink)" />
              <StatBlock label="Went to Nonwhite Veterans" value={`<${wealth.levittown.gi_bill_nonwhite_pct}%`} color="var(--grade-d)" />
            </div>
            <div className="serif" style={{ fontSize: 13, color: 'var(--ink-dim)', fontStyle: 'italic', marginTop: 16, lineHeight: 1.6 }}>
              The GI Bill of 1944 offered veterans the greatest wealth-building opportunity in American history. Out of 67,000 mortgages in the NY/NJ area in 1950, fewer than 1% went to nonwhite veterans.
            </div>
          </div>
        </div>
      )}

      {/* Compounding Calculator */}
      <div style={{ background: 'var(--grade-d-bg)', border: '1px solid rgba(192,57,43,0.3)', padding: 28, borderRadius: 4 }}>
        <Tick style={{ color: 'var(--grade-d)', fontWeight: 700 }}>The Compounding Calculator</Tick>
        <div className="garamond" style={{ fontSize: 20, color: 'var(--ink)', marginTop: 6 }}>What was the cost of exclusion?</div>
        <div className="serif" style={{ fontSize: 13, color: 'var(--ink-dim)', fontStyle: 'italic', marginTop: 4, marginBottom: 16 }}>
          Choose a year and a home price. See what the family that was locked out lost.
        </div>

        <div style={{ display: 'flex', gap: 32, alignItems: 'flex-end' }}>
          <div>
            <Tick style={{ display: 'block', marginBottom: 6 }}>Purchase Year</Tick>
            <input type="range" min={1940} max={1970} value={calcYear} onChange={e => setCalcYear(+e.target.value)}
              style={{ width: 200 }} />
            <div className="mono" style={{ fontSize: 14, color: 'var(--ink)', marginTop: 2 }}>{calcYear}</div>
          </div>
          <div>
            <Tick style={{ display: 'block', marginBottom: 6 }}>Home Price</Tick>
            <input type="range" min={5000} max={25000} step={500} value={calcPrice} onChange={e => setCalcPrice(+e.target.value)}
              style={{ width: 200 }} />
            <div className="mono" style={{ fontSize: 14, color: 'var(--ink)', marginTop: 2 }}>${fmt(calcPrice)}</div>
          </div>
          <div style={{ flex: 1, display: 'flex', gap: 32, justifyContent: 'center' }}>
            <StatBlock label="Value Today" value={`$${fmt(currentValue)}`} color="var(--grade-a)" />
            <StatBlock label="Wealth Generated" value={`$${fmt(gain)}`} color="var(--gold)" />
            <StatBlock label="Appreciation" value={`${Math.round(gain / calcPrice * 100)}%`} color="var(--ink)" />
          </div>
        </div>

        <div className="serif" style={{ fontSize: 13, color: 'var(--ink-dim)', fontStyle: 'italic', marginTop: 16 }}>
          The family excluded from buying this home didn't just lose a house. They lost every dollar of that appreciation, across three generations. At 4.5% annual appreciation (the historical US average).
        </div>
      </div>
    </div>
  );
}

window.TabBoom = TabBoom;
